## 向量化(Vectorization)
> 深度学习算法中，数据量很大，在程序中应该尽量减少使用loop循环语句，而使用向量运算来提高程序运行速度


In [3]:
import numpy as np
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)      #点乘
toc = time.time()
print c
print "vectorized version:" + str(1000*(toc-tic))+"ms"

c = 0
tic = time.time()
for i in range(1000000):
    c+=a[i]*b[i]
toc = time.time()

print c
print "for loop:" + str(1000*(toc-tic))+"ms"

249754.303413
vectorized version:3.99994850159ms
249754.303413
for loop:1044.00014877ms


**CPU与GPU**

为了加快深度学习神经网络运算速度，可以使用比CPU运算能力更强大的GPU。实际上GPU和CPU都有并行指令（parallelization instructions），称为Single Instruction Multiple Data（SIMD）。SIMD是单指令多数据流，能够复制多个操作数，并把它们打包在大型寄存器的一组指令集。SIMD能够大大提高程序运行速度，例如python的numpy库中的内建函数（built-in function）就是使用了SIMD指令。相比而言，GPU的SIMD要比CPU更强大一些。

## 逻辑回归向量化

<img src="../pic/c1-2/formula1.png">

在python的numpy库中可以表示为：

**Z = np.dot(w.T,X)+b**

**A = sigmoid(Z)**

## 梯度下降向量化

对于所有m个样本，dZ的维度是（1，m），可表示为：

+ dZ = A-Y
+ dw = 1/m*np.dot(X,dZ.T) 

+ db = 1/m*np.sum(dZ)

+ w = w - alpha*dw

+ b = b - alpha*db

## 广播（Broadcasting）

> 就是python中可以对不同维度的矩阵进行四则混合运算，但至少保证有一个维度是相同的

<img src="../pic/c1-2/image1.png">

    在python程序中为了保证矩阵运算正确，可以使用**reshape()**函数来对矩阵设定所需的维度。这是一个很好且有用的习惯。

## python的小技巧

In [4]:
a = np.random.randn(5)
a

array([-1.77895291, -0.31381631, -0.24494819, -0.07716835,  0.29886825])

    这条语句生成的a的维度是（5，）。它既不是行向量也不是列向量，我们把a叫做rank 1 array.如我们对a进行转置，还是会得到a本身。
    所以，如果我们要定义（5，1）的列向量或者（1，5）的行向量，最好使用下来标准语句，避免使用rank 1 array。

In [9]:
a = np.random.randn(5,1)
b = np.random.randn(1,5)
b

array([[ 1.39049414, -0.34162046,  0.09362724, -0.91976942, -0.2218661 ]])

In [13]:
#可以使用assert语句对向量或数组的维度进行判断，如果不是，则程序在此处停止
assert(a.shape == (5,1))

In [14]:
#使用reshape函数对数组设定所需的维度
a.reshape((5,1))

array([[ 0.31820565],
       [-0.21141833],
       [-0.54657599],
       [-0.11677999],
       [-0.15845233]])

In [5]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52, 8],
             [1.8, 135.0, 99, 0.9]])
A

array([[  56. ,    0. ,    4.4,   68. ],
       [   1.2,  104. ,   52. ,    8. ],
       [   1.8,  135. ,   99. ,    0.9]])